/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_cgc_wfx_NativeProgress */

#ifndef _Included_org_cgc_wfx_NativeProgress
#define _Included_org_cgc_wfx_NativeProgress
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_cgc_wfx_NativeProgress
 * Method:    notifyProgress
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_cgc_wfx_NativeProgress_notifyProgress
  (JNIEnv *, jobject, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
